# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Workflows

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]
  
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

env:
  message: ${{ secrets.ENV }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - shell: bash
 
      run: echo "I am the main message, I should not change from a fork"

    - shell: bash
      env:
        SUPER_SECRET: ${{ GITHUB_SHA }}
      run: echo "$SUPER_SECRET"
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
